### ISSUE TITLE
Adding DeviceService to ServiceManager causes a `System.IndexOutOfRangeException`

### ISSUE THREAD

**Issue by jvyden** [mosa/MOSA-Project#1105]
![image](https://github.com/mosa/MOSA-Project/assets/40577357/ed69bbe2-3789-407a-8888-5ceb5c578f94)

I tried to debug this myself, but I'm not sure what is causing this. I was able to narrow it down to the last line of this snippet:

```csharp
_serviceManager = new ServiceManager();
_deviceService = new DeviceService();

_serviceManager.AddService(_deviceService);
```

This is located [here](https://github.com/jvyden/BoringOS/blob/e4d47afc1077164d6ef1d21a6cfccc0f8015e61c/BoringOS.MOSA/Program.cs#L26), and is called from [here](https://github.com/jvyden/BoringOS/blob/e4d47afc1077164d6ef1d21a6cfccc0f8015e61c/BoringOS.MOSA/Boot.cs#L23).

I am using a fork of MOSA, but this shouldn't count as the changed code doesn't affect anything in this codepath.

**Comment by AnErrupTion** [comment]
You need to add DeviceService to the ServiceManager at least after this line:

```
            Mosa.DeviceSystem.Setup.Initialize(_hal, _deviceService.ProcessInterrupt);
```

**Comment by jvyden** [comment]
Yep, that was it. Thank you!
