### ISSUE TITLE
Merge Korlib.Plug.* and Runtime.* projects

### ISSUE THREAD

**Issue by GeroL** [mosa/MOSA-Project#1146]
Merge Korlib.Plug.* into Runtime.* projects

- [ ] Mosa.Plug.Korlib.x86 -> Mosa.Runtime.x86
- [ ] Mosa.Plug.Korlib.x64 -> Mosa.Runtime.x64
- [ ] Mosa.Plug.Korlib -> Mosa.Runtime

**Comment by tgiphil** [comment]
The plugs are separate from the VES runtime and should not be merged.
