### ISSUE TITLE
Switch statements with over 255 entries cause compiler to crash

### ISSUE THREAD

**Issue by tgiphil** [mosa/MOSA-Project#116]
The compiler crashes due to PHI operands exceeding the 255-operand limit.

**Comment by tgiphil** [comment]
This should be resolved now. Anyone have a test case?

**Comment by charsleysa** [comment]
Well there was that file in Driver library with names of devices that contained thousands of switch cases. Try adding that back into the solution.

**Comment by tgiphil** [comment]
The basic block data structure hold up to more than 256 blocks and branches. However, PHI stage still generates more than 256 operands, which causes the compiler to crash.
