### ISSUE TITLE
Create installer application using WiX

### ISSUE THREAD

**Issue by tgiphil** [mosa/MOSA-Project#126]

**Comment by charsleysa** [comment]
@tgiphil what would this be used for?

**Comment by tgiphil** [comment]
@charsleysa The installer would install pre-compiled components of the MOSA compiler and utilities. The goal being to reduce the level of complexity for new users by adding an installer, graphical user interfaces, and (hopefully) some integration with Visual Studio.

**Comment by tgiphil** [comment]
Note: There is an InnoSetup installer in my repo here: 

https://github.com/tgiphil/MOSA-Project/tree/setup/InnoSetup%20Installer
