### ISSUE TITLE
Add method parameter offsets calculations to MosaTypeLayout class

### ISSUE THREAD

**Issue by tgiphil** [mosa/MOSA-Project#135]
Add functionality to the MosaTypeLayout class to calculate stack offsets for method parameters. 

This will consolidate similar/duplicate methods in StackLayoutStage and BaseCallingConventionExtended classes.

**Comment by charsleysa** [comment]
@tgiphil is this completed?
I saw that your PR for implementing exception handling contained code along the lines for this.

**Comment by tgiphil** [comment]
@charsleysa No, this was moved to a future release. The code exists but in two difference places and re-calculated each time.

**Comment by tgiphil** [comment]
This can now be calculated with the layout class by sum the size of the parameters.
