### ISSUE TITLE
Optimizer hides bug related to load/store of 8 and 16 bits local variables

### ISSUE THREAD

**Issue by tgiphil** [mosa/MOSA-Project#147]
The following non-optimized instruction sequence loads the wrong value back into a register.

````
L_0000 X86.Movsx EAX [I4] <= a [EBP+8h] [I1]   ; Loads and extends signed byte parameter into EAX
L_0001 X86.Mov T_0 [EBP-4h] [I1] <= EAX [I4]   ; Stores one byte of EAX to stack
L_0002 X86.Mov EAX [I4] <= T_0 [EBP-4h] [I1]   ; Loads 32-bit value from stack into EAX
````
The bug is the store is only 8-bits, while the load is 32-bits.  The load brings 24-bit of random data (usually zeros in the tests, but not always). 

The optimizer removes the load/store and therefore masks the underlying bug.

The solution is either 1) to promote local variables to 32-bit size to match the stack, or 2) use a sign extended move to load back from the stack.

**Comment by tgiphil** [comment]
#1 is already implemented as part of the stack to register optimization but its use is restricted due to the presents of the AddressOf instruction. Appears that option #2 is the go forward solution.

**Comment by charsleysa** [comment]
@tgiphil could you please provide an example of where this is happening?

**Comment by tgiphil** [comment]
Test cases for SwitchI1 and SwitchI2 when optimizations are turned off.

Note: A fix is in my recently commit to my repo.
