### ISSUE TITLE
PCI BAR addresses not mapped to virtual space

### ISSUE THREAD

**Issue by tgiphil** [mosa/MOSA-Project#148]

**Comment by charsleysa** [comment]
How do you think we should go about implementing this?

What requirements are there and is there a standardized way that other OS's achieve this?

**Comment by vidstige** [comment]
Where should one look to investigate this? Any pointers to interesting files?

**Comment by vidstige** [comment]
@tgiphil any pointers if I were to look into this?

**Comment by tgiphil** [comment]
This is being solutioned within BareMetal.
