### ISSUE TITLE
Final testing and checks for v1.4 Release

### ISSUE THREAD

**Issue by charsleysa** [mosa/MOSA-Project#152]
Need to perform some basic peer review as final testing and checks before we release.
@tgiphil @kiootic @charsleysa

If everyone is happy with the current state then v1.4 will be published sometime after the 24th and before the 31st.

**Comment by tgiphil** [comment]
We should resolve the following before 1.4 is closed:

* Resolve CoolWorld crashing on VMware (or comment it out for now)
* Fix the last two remaining unit tests

And suggestions:

* Create pull request to merge kiootic changes to dnlib into 0xd4d/dblib

**Comment by charsleysa** [comment]
CoolWorld crashes on VMware due to the VMwareSVGAII driver. A simple temporary fix is to comment out the device driver attribute on the class. 

As for the last two remaining unit tests, they are part of the v1.5 milestone so in my opinion we should keep it that way and if it so happens that they are fixed by the time we release v1.4 then we can include it. 

Creating a PR to update the main dnlib repo would be beneficial but we need to check that it is compatible with their goals/use cases. @kiootic made some changes to allow the loading of a custom BaseClassLibrary.

**Comment by charsleysa** [comment]
The release will be locked in and available at the end of Jan 30th, probably around 11pm PST

**Comment by tgiphil** [comment]
+1

**Comment by charsleysa** [comment]
Closing for release.
