### ISSUE TITLE
How to debug the kernel

### ISSUE THREAD

**Issue by Arakis** [mosa/MOSA-Project#160]
How can i debug the running kernel when using for example, qemu? I found no documentation about that.

**Comment by charsleysa** [comment]
You must use the debugging tools provided by qemu. 

We have inhouse tools (e.g. TinySimulator) but these only work on Windows.

**Comment by Arakis** [comment]
TinyCPUSimulator was for MOSA, so it's no other official open source project! Wow, lot's of work is within MOSA.

I started the Simulator (open & compile + Start), but even after 5 minutes af waiting, the Display tab is still blank. But i see in the call stack, that the kernel is still running. Should i see something within the display? I used the hello world sample

**Comment by charsleysa** [comment]
With Reflection now in use TinySimulator now takes a while to get through the setup stages of the kernel. 

It is actually running but it's slow, we need to figure out if we can optimize it. It needs to be at least 10 times faster in order to handle the new kernel features.

**Comment by tgiphil** [comment]
Hi! How to debug the kernel? Very good question. Here are a few options:

1) Write debugging information to the console. (Works for me)
2) VMWare with the gdb debugger. (Never tried)
3) Use Mosa TinySimulator. (It's slow - 300,000 instructions per second).
4) Use Mosa Debugger (very beta).

The first option is the best at the moment. If you made changes to the compiler or runtime, run the xunit tests. It can catch the majority of issues without having to debug a kernel. Note: the unit tests are normally compiled with all optimizations on. So occasionally, I manually update the source code to run without optimization to make sure those continue to work as sometimes the optimizer "hides/fixes" bugs.

The TinySimulator is primarily for unit testing. Before TinySimulator, the code was compiled into a processes' memory and executed using mbunit framework, but when a unit test failed, it usually caused the whole process to crash or loop without a way for the test framework to recover. It would also takes about an hour or so to run. With TinySimulator, the execution and environment is simulated which also for it be controlled and monitored. It can also runs all the unit tests within a few minutes. In the future, we can add other platforms to the simulator and continue to run the test within Windows.

The Mosa Debugger is a small embedded kernel debugger that I have been working on. It uses the serial port to receive commands and return data. It works with real or virtual hardware. The biggest working feature is you can query memory from the target kernel and see it presented within a window. It's still very beta. I'd like to integrate it into the TinySimulator.

**Comment by tgiphil** [comment]
@charsleysa I'd love to make TinySimulator faster. Unfortunately, it was not written for speed. I have a few ideas, but the improvements would be in the 10-20% range and not 10x. I'd rather buy a faster processor or work more on the Debugger instead given that small margins of improvement. But I'm open to ideas!

What's Reflection doing at start up? Can we implement lazy evaluations, or have the compiler/linker do more work up front to presents the data structures more efficient?

I am planning to re-working the memory allocation to lazily build the free page lists, etc. That takes a lot of time during boot up within TinySimulator.

**Comment by charsleysa** [comment]
The Reflection is reading through all the types in assemblies and generating Type class and TypeInfo class instances. 

It is doing the bare minimum needed to have the driver system working. 

There may be some parts of it that I can speed up using cheats but it's only an issue for tiny simulator. Also lazy loading is what I planned to use for TypeInfo members such as methods, fields, properties, etc. 

On qemu it's a barely noticeable, fraction of a second processing time.

**Comment by charsleysa** [comment]
Closing due to question being answered.
