### ISSUE TITLE
Bug with mono / dnlib

### ISSUE THREAD

**Issue by Arakis** [mosa/MOSA-Project#171]
Problem:
- `MosaMethod.IsNewSlot` of `System.Object.Finalize` (and `System.ValueType.ToString` and lots of other types) is `false` when using mono. It's correct on windows (checked via debugger). I was not able to find out, why `IsNewSlot` is `false` on unix.
- `An element with the same key already exists in the dictionary` will occur when calling `methodStackSizes.Add(method, size)`. This occurs only on unix. `methodStackSizes` contains:
```
[0]	{[System.Void Default::InterruptISR0(), 0]}	System.Collections.Generic.KeyValuePair<Mosa.Compiler.MosaTypeSystem.MosaMethod,int>
[1]	{[System.Void Default::InterruptISR1(), 0]}	System.Collections.Generic.KeyValuePair<Mosa.Compiler.MosaTypeSystem.MosaMethod,int>
[2]	{[System.Void Default::InterruptISR2(), 0]}	System.Collections.Generic.KeyValuePair<Mosa.Compiler.MosaTypeSystem.MosaMethod,int>
...
```
I checked via debugging, that the entry, that want to be added, is really unique, when the exception occurs (yes it is unique).
The methods have different names, but have all the same signature! But `MosaMethod.Equals` (implementation of `IEquatable<MosaMethod>`) compares only against the signature! So i'm wondering, why the dictionary crashes only after several appendings.
I tried to rename `Equals` to `EqualsSignature` and re-added `Equals` with a more precise logic (checking method name and declaring type), than this does not occur again.

- In my test environment, i made a workarround for the `MosaMethod.IsNewSlot`-problem: When no Slot is found, a new one will created:
```
						int slot = FindOverrideSlot(methodTable, method);
                        if (slot != -1)
                        {
                            methodTable[slot] = method;
                            methodTableOffsets.Add(method.FullName, slot);
                        }
                        else
                        {
                            slot = methodTable.Count;
                            methodTable.Add(method);
                            methodTableOffsets.Add(method.FullName, slot);
                        }
```
(of course, i removed the exception in `FindOverrideSlot` and return `-1`.
But now, one of the both fixes (Slot problem / MosaMethod.Equals) occurs the next problem: `LinkerSymbol.Stream` is null in some cases. After setting in to a empty `MemoryStream` instance, compilation on unix works. HelloWorld starts, but CoolWorld crashes with Panic (1) on boot. I rechecked this on windows, and it occurs there, too. So i did not commited these changes (of course).

I checked this issues with the very latest source and the latest dnlib.

**Comment by charsleysa** [comment]
The exception with the dictionary having the same key is a known problem and is an easy fix.

Just replace mosa method with string and use the Method full name as the key.

**Comment by Arakis** [comment]
I fixed the Dictionary probme now (72cdeeffa457e5350ab3134bd94c42bb9c839f11), but the IsNewSlot problem is still there.

@kiootic, can you help to fix this issue? I can provide you access to a linux machine via remote desktop, if needed.

**Comment by kiootic** [comment]
It seems to be a problem with mono's compiler. I used mcs to compile Korlib and the methods you mentioned has no `newslot` set.

**Comment by charsleysa** [comment]
What's the status of this issue @Arakis?

Does it still exist with a fresh clone of the master branch from the main repo?

**Comment by Arakis** [comment]
@kiootic you are right, i can confirm this.
@charsleysa yes

i propose the following fix:
```
					if (method.IsNewSlot)
					{
						int slot = methodTable.Count;
						methodTable.Add(method);
						methodTableOffsets.Add(method, slot);
					}
					else
					{
						int slot = FindOverrideSlot(methodTable, method);
						if (slot != -1)
						{
							methodTable[slot] = method;
							methodTableOffsets.Add(method, slot);
						}
						else
						{
							slot = methodTable.Count;
							methodTable.Add(method);
							methodTableOffsets.Add(method, slot);
						}
					}
```
and FindOverrideSlot is return -1 instead of throwing an exception.
I tested this change on my machine on Windows an Linux and it works (HelloWorld and CoolWorld). XUnit, i cannot test it on Linux (in the moment, until we upgrade the xunit libs).

(it seems, the kernel panic, i wrote about in my first post, was because of wrong fix of the other `MosaMethod.Equals` bug - this is fixed (and already in the main repo)).

**Comment by charsleysa** [comment]
@arakis can you please run TestWorld on both Windows and Linux? 

And can you please run Xunit on Windows?

**Comment by Arakis** [comment]
@charsleysa all tests are fine

**Comment by charsleysa** [comment]
@Arakis can you please confirm whether this is still an issue?

**Comment by charsleysa** [comment]
Closing this as issue is considered resolved.
