### ISSUE TITLE
Static constructors allocate memory before Runtime.Setup

### ISSUE THREAD

**Issue by Arakis** [mosa/MOSA-Project#196]
Uncomment in VirtualPageAllocator.cs:95 this line:
```c#
Assert.True(initialized, "VirtualPageAllocator is not initialized");
```
When run the OS, you will get the the above error. In the stack you will see, that `VGAText.cctor` is occurring this allocation. This problem is by design (in the moment).

This field initializer occurs the allocation:
```c#
		private static byte[] VGAText80x25 = new byte[] {
		/* MISC */
			0x67,
		/* SEQ */
			0x03, 0x00, 0x03, 0x00, 0x02,
		/* CRTC */
			0x5F, 0x4F, 0x50, 0x82, 0x55, 0x81, 0xBF, 0x1F,
			0x00, 0x4F, 0x0D, 0x0E, 0x00, 0x00, 0x00, 0x50,
			0x9C, 0x0E, 0x8F, 0x28, 0x1F, 0x96, 0xB9, 0xA3,
			0xFF,
		/* GC */
			0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x0E, 0x00,
			0xFF,
		/* AC */
			0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x14, 0x07,
			0x38, 0x39, 0x3A, 0x3B, 0x3C, 0x3D, 0x3E, 0x3F,
			0x0C, 0x00, 0x0F, 0x08, 0x00
		};
```

Ideas:
- Avoid all initializers, that allocates memory. This would be the most unflexible idea.
- Adding a [InitializationStage(level)] attribute. By default, only level 0 will be initialized, after Runtime was setup all other.
- Create a micro runtime (with runtime + memory management) and load the rest of the kernel lazy. This would be clean, but the most complex one.
- Lazy initialization of the Types on demand. We should check how the .net jitter does this. Maybe we should use a similar way like the jitter compiles methods on demand: All methods have a small ASM stub, that jumps directly to the "compile" method. The stub will replaced then with the generated asm code.

What do you think?

**Comment by charsleysa** [comment]
Thanks for finding this problem, I spent days trying to find it. 

The problem seems to be a bug with the Static Allocation Resolution Stage. 

That stage allocates memory during compile time to avoid the memory allocation issue.
