### ISSUE TITLE
Getting the pointer address of "this" fails

### ISSUE THREAD

**Issue by Arakis** [mosa/MOSA-Project#200]
When using the below code, the compiler crashes.
```c#
unsafe private uint AddressOfThis
{
	get
	{
		fixed (ELFStructure* p = &this)
			return (uint)p;
		//fixed (void* p = &Type) //getting the address of the first field fails, too
		//	return (uint)p;
	}
}
```

Even when this will work i want to ask, if there's a way for "fast" getting the address of the current structure / this context, maybe with a Native-helper method / compile helper.

**Comment by charsleysa** [comment]
Why do you need the address of this?

**Comment by Arakis** [comment]
Why are you asking why i need this? This is a bug / not implemented feature. It needs to work.

I can use workaround, for example give the address to the method as additional paramter, or use a parent struct, that holds the address and have all its methods, but these are workarounds than. It makes more work as needed.

**Comment by charsleysa** [comment]
There are already ways of getting the address of a struct. 

Why you need the address is a different matter. 

Can you please post the final x86 code produced by Explorer for this method?

**Comment by Arakis** [comment]
This is not possible, because the compiler crashes. `Missing label while resolving patches`. But when adding a additional method to the source (that calls the property), than it will not crash (i did not checked if it's runable yet).

Wich ways do i have to get the address of a struct, when i'm in a method of this struct?

**Comment by charsleysa** [comment]
There are helper methods in Mosa.Internal.Intrinsic which can do this. The methods are self explanatory. 

They should be used sparingly.

**Comment by tgiphil** [comment]
The fixed keyword is not yet supported. 

Plus this is not work - the Garbage Collector could move the object after its unpinned.

**Comment by Arakis** [comment]
Not when you use a struct on a absolute address, outside of the regular heap. I do not want use the fixed keyword, but c# will not compile it, when not using.

**Comment by Arakis** [comment]
My example in my first post works now, thanks @tgiphil !
But there are some remaining problems.

https://github.com/mosa/MOSA-Project/blob/3f1cb92f518a7a3fdc2bb2cccc0ca121cbaa0384/Source/Mosa.Platform.Internal.x86/StringBuffer.cs#L35-L40
```c#
fixed (void* ptr = &this)
  return (char*)(((uint)ptr) + 4);
```
Will result in a compiler crash: `Missing label while resolving patches` (MachineCodeEmitter.cs:276)

```c#
return (char*)((uint)(Mosa.Internal.Intrinsic.GetValueTypeAddress(this)) + 4);
```
Why this does not work, i dont know, it simply returns the wrong value, it think.

So my workarround is here:
```c#
uint ui;
fixed (void* ptr = &this)
	ui = (uint)ptr;
return (char*)(ui + 4);
```

**Comment by Arakis** [comment]
This simple one does not work, too (direct return of pointer without any casting):

```c#
fixed (MultiBootMemoryMap* ptr = &this)
	return ptr;
```

**Comment by charsleysa** [comment]
Closing as bug no longer exists.
