### ISSUE TITLE
Bug in PlugSystem

### ISSUE THREAD

**Issue by Arakis** [mosa/MOSA-Project#207]
Remove this code:
https://github.com/Arakis/MOSA-Project/blob/5f13dfd449a39a96b078a6296a62d4779e1ffe66/Source/Mosa.Kernel.x86/Helpers/DebugImplementation.cs#L22-L27

And call it in Boot.cs of CoolWorld:
```
Debug.Fail("test");
```
Nothing will happen. I was not able to reproduce this issue within a TestCase (in TestWorld).

It seems, the original Fail(string) method calls the original Fail(string, string) method, not the plugged one.

**Comment by charsleysa** [comment]
I don't think this is a bug, you'll have to wait until @tgiphil comments on this.

The reason I don't think this is a bug is because that's the intended ability of plugs.

**Comment by Arakis** [comment]
But in a isolated test case, it worked like expected. So, it's confusing that i was not able to reproduce it in the TestCase.

**Comment by Arakis** [comment]
The matter was the missing DEBUG symbol in korlib. Now all is working like expected.
