### ISSUE TITLE
Method to evaluate if a method can be inlined

### ISSUE THREAD

**Issue by tgiphil** [mosa/MOSA-Project#222]
**Starting Points:**

Inlined methods are inserted prior to platform specifics stages and IR optimizations stages re-run. Methods are evaluated to be inlined after IR-level optimizations and prior to platform specific stages based on the following criteria:

* Virtual methods are not inlined.
* Methods that contain exception-handling blocks are not inlined.
* Methods that contain complex control flow, such as loops, are not inlined.
* Methods with value type as parameters are not inlined (until the compiler can promote the value type on the stack into virtual registers).
* Methods that have greater than 24 IR instructions are not inlined.
* The cost of using an inlined method must be less than the cost when not inlined. (See below.)
* [added] All IR-level optimizations must be enabled.

**Heuristic cost modeling:**

1. Estimate the cost of the method call when not inlined: one instruction for each 32-bits of parameter data for the store and again for the load and a fixed overhead for stack increment & decrement and call & return. So a rough cost of: ((total byte sizes of all parameters / 4) * 2) + 4, or 2 if there are no parameters.
2. Estimate the cost of the inlined method: callee method IR instruction count (excluding instructions in prologue and epilogue blocks) multiplied by 1.19 for optimized code. Or multiplied by 2.12 for non-optimized code. These numbers are based on the current average IR to x86 instruction ratio.

**If the inline cost is less than the non-lined cost, then inline the method.**

**Further heuristic enhancements:**

* If the method is called from within a loop, then increase the non-inlined cost. *Multiple by 2.*
* If the method contains a method call that is not inlined, then increase the inline cost.  This adjusts for the call site overhead having a higher average IR to x86 instruction ratio. *Add 4 per call.*
* If the method has more parameters than the platform’s available registers, then increase the non-inline cost to adjust for spilling costs. *Multiple by 2 (or add 2 per parameter after 4).*
* On x86 platform, methods with IR instructions dealing with 64-bit values should not be inlined. The instruction expansion to handle 64-bit values in almost all situations have a greater inline cost. 
* [added] If the method has the AggressiveInlining attribute, the maximum of IR instructions and the non-inlined method cost are increased. *Add 8 additional IR instructions and multiple the cost by 2 respectively*. This would inline the method more aggressively.

The adjustment values are off-top-of-my-head estimates. They should be replaced by values derived from testing and imperial analysis.

**Comment by Rew** [comment]
Other things I'd add to the feature spec would be using MethodImplAttribute for NoInlining (never inline) and AgressiveInlining (inline wherever possible regardless of cost). 

I don't have enough experience outside of x86 to answer this, but would it make sense to make some of the cost evaluation platform specific?  Is there enough of a difference in call overhead between platforms for this to matter?

Also, I'd argue that non-optimized code should never be inlined since in-lining could be considered an optimization and makes stack traces less accurate.

**Comment by tgiphil** [comment]
@Rew I don't see a problem adding those attributes as additional hints.

For the AggressiveInlining, the maximum of IR instructions and the non-inlined method cost increased, by 8 instructions and by 2 times respectively. This would inline more aggressively.
