### ISSUE TITLE
MOSA Launcher fails to create boot images

### ISSUE THREAD

**Issue by charsleysa** [mosa/MOSA-Project#248]
MOSA Launcher fails to create boot images.

There seems to be a bug in the BootImage utility library which fails to generate images properly.

**Comment by tgiphil** [comment]
The issue is the new Syslinux v6.03 installation has changed significantly since v3.72. 

Until this is resolved, the default build is ISO to avoid the issue for now.

**Comment by tgiphil** [comment]
Added back previous version of Syslinux as an option. So virtual disk images (along with ISO) are now available. I will close this ticket and create new ticket for adding Syslinux v3.72 support.
