### ISSUE TITLE
MOSA Launcher crashing while building an OS

### ISSUE THREAD

**Issue by CSharpLover** [mosa/MOSA-Project#258]
Yes, don't know why...

Reinstalling Windows didn't fix it, my all other tries, too...

I'm saw this error when i look the debugger output:

An unhandled exception of type 'System.Collections.Generic.KeyNotFoundException' occurred in mscorlib.dll

Then application crashes...

This is the last message from Launcher before crash:
Compiling: 1,74 secs: Stage Ended: SSESetupStage

Don't know why i'm having this bug, it sometimes being fixed, and sometimes being started again...

**Comment by charsleysa** [comment]
@CSharpLover does this happen on a Debug build or a Release build?

**Comment by CSharpLover** [comment]
Sorry i forgot removing this, it is happening on Release build, after last commit it is fixed (Changed build to Debug)
