### ISSUE TITLE
os crash: kernel panic 

### ISSUE THREAD

**Issue by mesutpiskin** [mosa/MOSA-Project#344]
What causes this error.
My launcher settings:
![screenshot_1](https://cloud.githubusercontent.com/assets/3519662/17544544/ab501a9a-5ee0-11e6-868c-70485fd354e3.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/3519662/17544543/ab4ecd5c-5ee0-11e6-959f-41187c2556ea.png)

**Comment by tgiphil** [comment]
@mesutpiskin We are aware of the issue but don't know the root cause yet.

**Comment by mesutpiskin** [comment]
@tgiphil Thanks for answer, i hope all goes well

**Comment by carverh** [comment]
Figured it out, the new Keyword uses memory
