### ISSUE TITLE
Can I do manual memory management?

### ISSUE THREAD

**Issue by kameko** [mosa/MOSA-Project#345]
I'm not too comfortable with the idea of a garbage collector in the kernel, I'd prefer to do manual memory management in the kernel for my own OS, especially for the option of having an RTOS. I noticed some methods for memory management, but do they work? How do they work?
- How would I call Clear()? I don't know of any method to get the size of an object and it's location in memory to pass to Clear() and I didn't see one in the MOSA source. Does one exist?
- What would I have to call Clear() on? Anything prefixed with the "new" operator? Are there any kind of sneaky allocations happening anywhere else? Does Korlib do any allocations that I'd have to modify with freeing it's memory?
- Is there a Free() method anywhere that I can just pass an object to directly, or would I have to write my own using Clear()? I didn't see any kind of Free()-like method in the source. I can write my own using Clear() if MOSA has some kind of sizeof() method, but just checking if Free() exists already.

Thanks to anyone who can answer me. And hopefully this information will be relevant to anyone else who wants to manual memory management in MOSA.

**Comment by charsleysa** [comment]
Hi @kameko,

At the moment we have very little memory management API's.

The tricky part with manual memory management is that the CLR does a lot of memory allocations behind the scenes which you can't get to with standard C# code.

The way we get to it is by using compiler tricks when we compile the CIL to native machine code.

There is a common piece of code that gets called during this process called [AllocateObject inside the GC class of the Runtime library](https://github.com/mosa/MOSA-Project/blob/master/Source/Mosa.Runtime/GC.cs). This may suit your needs.

A lot of the Runtime level memory management will (such as `Clear()`, `Free()`, etc) will need to use compiler tricks to redirect them to C# code in a way that we can manipulate memory.

This isn't difficult to implement but we currently have higher priority bugs on our TODO list.

I hope this information helps and, as always, any contributions that align with the project's goals would be most welcome.
