### ISSUE TITLE
how to create a new project?

### ISSUE THREAD

**Issue by asm2620** [mosa/MOSA-Project#351]
I compiled the mosa, then I created a new Console Application and refrence to Mosa.Kernel , ... but when I put it into mosa launcher, it didn't do any action.
But when I give your demos like mosa.coolworld it runs in qemu.
I copied the mosa.bootloader to another folder and compiled again, but project didn't run.
Hoe we must build our own os with mosa?

**Comment by tgiphil** [comment]
The quickest way is to copy or updated the Mosa.HelloWorld.x86 project.

**Comment by asm2620** [comment]
I copied it but there's no different.
