### ISSUE TITLE
Using AOT compiler

### ISSUE THREAD

**Issue by bencz** [mosa/MOSA-Project#367]
Hi!
It's possible to use the AOT compiler to generate the assembly code for some small codes ( just to look at generated assembly code )
For example, I have this small code:
```
namespace Teste
{
public class Tete
{
  public string a;
  public Tete(string t) { a =t; }
}

public class Hello1
{
   public static int Main()
   {
      Tete txt = new Tete("aaaaa");
      txt.a = "lala";
      return 0;
   }
}
}
```
So, I build this code with CSC compiler, and, if I want to build the generated exe with MOSA AOT compiler to look at generated assembly, it's possible ?
If yes, how I can do it ?

**Comment by Jan4V** [comment]
Hi, the AOT compiler currently requires you to use Mosa.Platform/Runtime for compiling.
That means that at this point this isnt really possible. The foundation is there, but official support is only for building kernels. Atleast that was the situation when I try to do similar stuff a few months ago.
If you want to compile your application, you can do so similarly to kernels, by using the Launcher, or by invoking the compiler directly from the command line. It is located inside the bin directory assuming you built the solution. However without using Mosa.Platform."yourplatform"/Mosa.Runtiume."yourplatform" in your code, it might just not work/crash while compiling.

Quoting tgiphil from February (when I asked about using Mosa for compiling applications): "MOSA is really merging an application with runtime + OS. It'll be hard to seperate those components out. Traditional applications support is still very far into the future. It requires a lot of other things."

**Comment by tgiphil** [comment]
@bencz Thanks for your interested in MOSA. The Mosa.Tool.Explorer.exe tool allows you to paste & compile a code snippet and review all the stages of the compilation process, including the binary output before linking. 

If the code snippet tries to instantiate objects, it would require several code libraries also be compiled. In this specific case, the Explorer tool does not support this at this time.

The workaround is to include the code snippet into one of the test OS projects and use either the Explorer tool to review the output, or the Mosa.Tool.Launcher tool and check the "NASM File" or "ASM File" option to emit ASM disassembly.
