### ISSUE TITLE
Launcher Tool - Include file(s)

### ISSUE THREAD

**Issue by furesoft** [mosa/MOSA-Project#382]
add function to add a option in the tools launcher to integrate an file in the resulting image. purpose is to add filesystem container for live system

**Comment by tgiphil** [comment]
Great idea! The functionality is already in CreateBootImage tool. It just needs to be added to Launcher tool. Both tools utilized the same libraries for creating the image with the FAT file system.

**Comment by tgiphil** [comment]
FYI - The backend code already support this but there is no command line arguments to capture the information.
