### ISSUE TITLE
add more scancode maps

### ISSUE THREAD

**Issue by furesoft** [mosa/MOSA-Project#396]

**Comment by robot9706** [comment]
I could create a map for hungarian keyboards.

**Comment by tgiphil** [comment]
Which ones? All is too broad.

BTW. Please only generate issues for items that are necessary for you, or things you are willing to contribute. Otherwise, the issue list can grow almost infinitely. Thanks.

**Comment by tgiphil** [comment]
Closing; no specific enough. 

@robot9706 If you create the Hungarian scancode, please create a new issue for this. Thanks!
