### ISSUE TITLE
Question about future plans

### ISSUE THREAD

**Issue by ArsenShnurkov** [mosa/MOSA-Project#432]
What do you think about this plan:
https://github.com/dotnet/corert/blob/master/Documentation/high-level-engineering-plan.md
?

looks very similar to this project. Does this mean that this project is dead (like <a href="https://github.com/Pash-Project/Pash">Pash</a>)?

**Comment by tgiphil** [comment]
It’s a good plan, but they have hit roadblocks, particularly with the LLVM compiler which doesn’t support the stack unwinding required by the .NET VIrtual Machine. 

We continue to work on MOSA. :)
