### ISSUE TITLE
Use compiles file

### ISSUE THREAD

**Issue by furesoft** [mosa/MOSA-Project#433]
Is it possible to use a compiled sample file?

**Comment by furesoft** [comment]
Asm

**Comment by tgiphil** [comment]
I don't understand the request. Are you trying to link in another object file?

**Comment by furesoft** [comment]
Yes like I have a precompiled driver and I want to link

**Comment by tgiphil** [comment]
It’s trivial to include the pre-compiled objective code. The real challenge is that code is not aware of the existing kernel framework or API - things like memory allocation, interrupt handler callbacks, etc. 

The only workable solution is to incorporate the source code of the driver within MOSA device driver system; which by the way is an area of current development.
