### ISSUE TITLE
installer

### ISSUE THREAD

**Issue by furesoft** [mosa/MOSA-Project#480]
how can i make a installer that copys the os to the harddrive?

**Comment by tgiphil** [comment]
@furesoft Try using the DD utility with the .IMG file. For example:

`dd of=\\?\Device\HarddiskX\PartitionX if=bootimage.img bs=512 –progress`


Note: Be very **careful** about selecting the correct Hard Disk and partition!

**Comment by furesoft** [comment]
but i want that on a machine that has no os and has no dd
