### ISSUE TITLE
Disable reflection option

### ISSUE THREAD

**Issue by tgiphil** [mosa/MOSA-Project#572]
When reflection is disabled, the reflection metadata could be excluded to save memory.

This would be extremely valuable and necessary for low memory platforms.

**Comment by charsleysa** [comment]
Just a note, this may possible affect the use of generics as some code may possibly need reflection Metadata for some generics to work properly. (AFAIK we still have an incomplete generics implementation).

**Comment by charsleysa** [comment]
Related: #331
