### ISSUE TITLE
Omit result type in symbol name

### ISSUE THREAD

**Issue by arakis** [mosa/MOSA-Project#580]
Symbol names should not contain the result type. It's useless, harder to read (and to type) when using them with GDB, and when using symbol names in command line scripts, the space in the name makes life harder.

```
System.Void lonos.kernel.core.Start::Main()
```
to
```
lonos.kernel.core.Start::Main()
```

if it's ok, i will prepare a patch.

**Comment by tgiphil** [comment]
Note: *Every* instance of Method.FullName would need to change. VS refactoring tool might be helpful to do this.

**Comment by tgiphil** [comment]
@charsleysa I don't believe .NET methods can be overloaded with a different return types.

**Comment by charsleysa** [comment]
@tgiphil yes you are correct, I am confusing overloading with a side effect of MOSA compilers concreting of generic type parameters.

Unless this has changed I believe that when concrete types are generated during the compilation process you end up with methods which only differ by return type.

For example, `IEnumerator<T>.Current` Property is a getter which under the hood is a method. It has the signature `public T Current { get; }` which then gets duplicated for each concrete type of `IEnumerator<T>` (so in essence you have a copy of the getter for each type that is used with the enumerator). 

If this is no longer the case then I have no issue with removing the return type from the symbol.

**Comment by arakis** [comment]
Solved in #692.

**Comment by charsleysa** [comment]
Upon further debugging and reading of the CLR spec, this issue needs to be re-opened as it is actually possible for two methods with the exact same name and input parameters with only the return type being different. (For a real example, see the `System.IntPtr` class, Line 92 - 109, all three operators have the exact same name and input, only differing by return type)

As such, the full name of a method *MUST* include the return type in order to maintain uniqueness, and the signature *MUST* include the return type in order to maintain correctness. Not doing so causes clashes in the type system and bugs arise from these clashes.

I propose we revert changes that were made in https://github.com/mosa/MOSA-Project/pull/692.

**Comment by arakis** [comment]
First of all, i have good reasons for having a shortened symbol name (explained in #690) and if you want to revert it, you need to add hook to make it possible to customize the symbol name. This was exactly what I did here: https://github.com/mosa/MOSA-Project/pull/690/files

This first patch didn't modify any symbol names per default, only if you use the custom Delegate. That was my goal. The only problem was, I used a global static delegate, Phil don't want such global Properties. But MosaTypeSystem does not have access to compiler options.

https://github.com/dotnet/docs/blob/master/docs/standard/language-independence.md
```
CLS Rule 38: Properties and methods can be overloaded based only on the number and types of
their parameters, except the conversion operators named op_Implicit and op_Explicit, which
can also be overloaded based on their return type.
```

You're right, i din't knew this before. But as you see, its the only exception for op_Explicit and op_Implicit.

So, make an exception for op_Implicit/op_Explicit or add an compiler hook. If you tell me what you preffered way is, i can implement such hook or exception. If using a hook, we need to define how to pass the hook from Compiler Options to TypeSystem (dependency problem).

**Comment by charsleysa** [comment]
That rule only applies to CLS-compliant code. Any code that chooses not to be CLS-compliant doesn't have to follow that rule while still being perfectly executable by the CLR.

The MOSA compiler should handle any valid CIL that can be run on the CLR, including non-CLS-compliant code.

I understand you have a need for shorter symbols for your DWARF so we should come up with a compressed version of the symbols that can optionally be used. I would recommend keeping the return type as you may have situation with 2 or more symbols clashing ( / overwriting each other depending on how you use the symbols) as return type is part of signature uniqueness.

**Comment by tgiphil** [comment]
How about we compromise by adding the return types at the end of the method for op_Explicit and op_Implicit? 

I personally like the shorter method names.

**Comment by charsleysa** [comment]
@tgiphil PR #734 reverses to use full names as that was the only way to get the fix working.

If it's a display issue then we can add a new display name, but the proper full name needs to follow the CLR uniqueness rules.

**Comment by tgiphil** [comment]
Let's make two fields:

Thoughts:

1. Rename the current **FullName** property to **SymbolName** with a change to include return value for op_Explicit and op_Implicit.
2. Add new property called **FullName** based on the CLR requirements. 
3. Update the metadata emitter to use **FullName** instead of **SymbolName**.

**Comment by charsleysa** [comment]
@tgiphil it's not just Metadata that requires the full CLR signature, most of the compiler relies of the uniqueness, I think instead fullname should be changed to be fully CLR compatible and symbol name to be added with a shortened version.

**Comment by tgiphil** [comment]
Won’t the second part of #1 keep all the names unique?

**Comment by charsleysa** [comment]
@tgiphil unfortunately no. The CLR is not limited to just allowing op_Explicit and op_Implicit to have different return types. The CLR allows pretty much any method to have different return types.

I'm happy to update #734 with a new SymbolName property that has a shortened name with return type removed but it needs to be understood that whatever uses that property will potentially have duplicate symbols so can't be relied on for uniqueness.

If shortness is such a desired feature then why not used a hash of the unique fullname?That would provide the shortest symbol while maintaining uniqueness.

**Comment by tgiphil** [comment]
Okay -- then let's just put the return type at the end of the method name and parameters. Just like in the Explorer Tool.

**Comment by charsleysa** [comment]
@tgiphil yea can do, the original reason we had the return type first was to match the Microsoft tools (specifically ILDASM I think) so we could effectively copy paste to search for things, but I think we can start moving away from that.

So is symbolname still needed?

So to clarify, this is what will be changed in the #734 PR:
1) fullname will always include return type but with the return type at the end
2) symbolname will be a shortened version of fullname

**Comment by tgiphil** [comment]
Just #1 and #3.

**Comment by arakis** [comment]
This will only solve avoiding the Spaces within the name (Correct me, if I'm wrong), but not the root of the problem. It's fells more a quick fix. A Fully Qualified ReturnType at the End of the Name is still impracticable.

The clean way to go:
- Separating FullName from SymbolName.
- Keep FullName as it is or whatever is required.
- SymbolName defaults to FullName, but  **without ReturnType** except for op_Implicit/op_Explicit. In that case Return Type is appended, without any space but a ":" as separator.
- Adding an overridable hook/delegate/event to Customize GetSymbolName(MethodDecl).

With a hook, the developer (consumer of Compiler) can do the following custom approach:
```
(Pseudo-Code, part of Developer / hook, not part of Compiler)
GetSymbolName(MethodDecl)
  if(MethodDecl.HasAttribute(ExportNameAttribute))
    return MethodDecl.GetAttribute(ExportNameAttribute).ExportName
  else if(otherCustomDondition)
    return StripPrefixOfNamespace(...) // really short SymbolName if author of hook knows, there are no collisions.
  else
    return base.GetSymbolName(MethodDecl)
```

If developer does not hook that method, it defaults to FullName  **without ReturnType**, except for op_Implicit/op_Explicit.

An Alternative to a hook would be:
- Adding ExportNameAttribute to official Mosa Sources
- If Method is not decorated with that Attribute, it defaults to FullName **without ReturnType**, except for op_Implicit/op_Explicit.
Without a hook, developer is not able for example stripping the first Part of the NameSpace (like "Mosa." or "Lonos.", but this is an acceptable tradeoff.

If you don't want separating SymbolName from FullName, there's no clean way. One way could be to hook/customize FullName, but this is more a quirk, because you explained (and you're correct) the FullName requires the ReturnType.

**Comment by tgiphil** [comment]
We will add an option to strips out the return type when the linker emits the symbol name into the ELF file. At this time, there is no strong necessity to develop/support a plug/hook structure for MOSA.

**Comment by arakis** [comment]
@tgiphil for the first run, this is an acceptable tradeoff. Please don't forget to strip all whitespaces, too, and do not forget DWARF symbols.
