### ISSUE TITLE
Duplicate generic methods

### ISSUE THREAD

**Issue by tgiphil** [mosa/MOSA-Project#626]
The metadata loader creates duplicate generic methods in the type’s method list.

Bug needs to be fixed here:

https://github.com/mosa/MOSA-Project/blob/cf27f7ee4eafd3fdf1a13a1983f5f0947f9903d3/Source/Mosa.Compiler.MosaTypeSystem/Metadata/MetadataLoader.cs#L459

Once resolved, the hack here needs to be removed:

https://github.com/mosa/MOSA-Project/blob/6d96906dce5d015e869c342b8d000ee1f445cd27/Source/Mosa.Compiler.Framework/MosaTypeLayout.cs#L713-L715

**Comment by charsleysa** [comment]
Do the method signatures differ in any way? If so then that would explain the duplication.
