### ISSUE TITLE
Kernel Panic when setting int property

### ISSUE THREAD

**Issue by furesoft** [mosa/MOSA-Project#651]
![image](https://user-images.githubusercontent.com/4117602/61641788-0d561180-aca0-11e9-8ad2-dbc4184b8f2f.png)

**Comment by tgiphil** [comment]
Please zip up the project and I’ll take a look.

**Comment by furesoft** [comment]
here is my repo: https://github.com/furesoft/FureOS

**Comment by tgiphil** [comment]
I wasn't able to re-create the issue - the project compiled and executed without an issue:

https://files.gitter.im/tgiphil/qU8m/image.png

**Comment by furesoft** [comment]
the jmp execution code is commented it should be run in loop

**Comment by tgiphil** [comment]
Thanks; I was able to re-create the problem.

**Comment by tgiphil** [comment]
I don’t see anything wrong with the code. Also, I was able to recreate the problem without uncommenting the line in the jump class. I’ll need to attach the debugger to narrow down the issue.

**Comment by arakis** [comment]
Is this issue still arround?
