### ISSUE TITLE
Enter Long Mode for x64 Platform

### ISSUE THREAD

**Issue by tgiphil** [mosa/MOSA-Project#670]
Enter Long Mode:

1. Setup page tables & identity map
2. Enable paging
3. Enable 64-bit GDT
4. Enter long mode

This should be called by multiboot prior to entry into MOSA generated x86 code.

**Comment by tgiphil** [comment]
References:

* https://wiki.osdev.org/Setting_Up_Long_Mode
* https://wiki.osdev.org/Entering_Long_Mode_Directly

**Comment by tgiphil** [comment]
Sample code from OSDEV:

[EnterLongMode.txt](https://github.com/mosa/MOSA-Project/files/3470463/EnterLongMode.txt)

Needs the following updates:

1. Exits by returning to caller

Prerequisite: Caller preserves register upon entry (specifically EAX and EBX for multiboot) for later user after entering long mode.

**Comment by tgiphil** [comment]
This is implemented but needs to be debugged along with the 64-bit opcode generation.

**Comment by AnErrupTion** [comment]
Not needed anymore as we are implementing Limine, which handles that for us automatically.
