### ISSUE TITLE
Compiler hooks

### ISSUE THREAD

**Issue by arakis** [mosa/MOSA-Project#732]
Purpose of this suggestion:

Instead of having tons of special Attributes and CompilerOptions for very special use cases (for example when you are developing a real operating system), we should add some kinds of hooks to customize some workflows. I know we have CompilerStages and Extensions, but for that the specific Stages itself are not customizable. So, here are 4 simple, but very powerful hooks:

The idea is to add hooks to the compiler/options. Each hook is a delegate a something similar (for example as overridable method, see at the end of this text). Per default, they are null (default behavior).

### bool? ForceInline(MethodDef):
	determines of the method should inlined or not. If it returns null, it's default behavior (for example seach for MethodImpl)

Use case: see #711
  
### string GetPlugMethod(MethodDef):
	returns the fully qualified path to a PlugMethod of the given MethodDef. If it returns null or empty, the default behavior is used (=searching for PlugAttribute)
  
Use case: Using the plugs from korelib.plug.x86, but overwriting some of them. Currently, this is not possible, except copy the whole source and make the modification.
  
### string GetCallTargetMethod(CallSite)
	returns the fully qualified path to a method.
	
Sample use case, hook written as pseudo code:
		
```
string GetCallTargetMethod(CallSite)
{
	var callerMethod = CallSite.MethodBody.Method;
	var targetMethod = CallSite.TargetMethod;
	if(targetMethod == "Monitor::Enter" && callerMethod.Attributes.Contains(UninterruptableAttribute))
		return "UninterruptableMonitor::Enter"
}
```	

### string GetAllocateObjectMemoryMethod(CallSite, TypeDef):
	returns the fully qualified path of a GC:AllocMemory method.
  
Sample use case: Having objects allocated in different isolated memory zones. CallSite is required to determine who is allocating, and TypeDef is required to determine what object should be created (this will include, arrays, too).

### Delegate vs Overridable Method

An improved version would be: Instead of using a delegate, its more usefull to overwrite a method. So you can decide individual of you first check the input parameters and than return a custom result, or maybe calling base.HookBaseMethod, checking the result of default behavior and then you may modify it.

**Comment by tgiphil** [comment]
My two cents: The first two goals, related to inlining and plugs, could be handled by text-based compiler configuration file. The other goals are orthogonal to the project's primary goals and are better suited to be solved without additional compiler specific assistance (or not at all). For example, the delegate vs overridable method is solvable by using plugs.

**Comment by arakis** [comment]
> The first two goals, related to inlining and plugs, could be handled by text-based compiler configuration file.

Since you may allow wildcard (Namespace.*/Type.*), its really fine. So i can mark it as done. And if you allow Plugs defined in config-file, so I'm able to use custom plugs (override existing Plug-attributes without copy whole source and make the modifications).

> For example, the delegate vs overridable method is solvable by using plugs.

You misunderstood. It's not a fifth featuer reqeust, it's an implementation detail. I mean the hook itself. You can implement a hook in two different ways: HookActionDelegate = myAction. Or: Override HookAction. Latter is more powerful because you can work with the base / default implementation.

Feature 3 and 4 are nearly impossible to implement without a hook, a configuration file would far too inflexible, as its wants to analyze the calling context "CallSite".

Where is the problem just to provide a way to resolve a method destination via hook? Of course, I can fork Mosa-Project and make my own patches in the that fork, but that should not be the way to go. Mosa will benefit from that feature. And by the way: Working with patch-sets is time-consuming / slows down development / upgrading to new compiler versions.

Mosa is a great compiler. With some little tweaks you can open big horizons and new possibilities, more than you "plan" for Mosa itself (I know you follow mostly your managed goal). Just as example: Only with the Embedded ASM-Code it was able to create a powerful kernel that's not only depending on predefined, hardcoded Intrinsics.
