### ISSUE TITLE
Integrations Tests with Github Actions

### ISSUE THREAD

**Issue by arakis** [mosa/MOSA-Project#744]
I integrated our integrations tests with GitHub Actions. They are faster and run in parallel (For example Windows and Linux at the same time), even for multiple commits in a row, and the output is much more readable.

In the last days, I noticed two problems regarding integrations tests:
- Ignoring Test Fails
- Disabling Tests (for example Test on Windows).

Because of these two Problems, I want to underline the following facts:
- Never Ignore Failing Tests. If a Test fails - fix it. Do not proceed with other features. A failing Test is *always* a blocking issue. In the best case, just don't merge the PR, if you see that Test is failing.
- Since GitHub Actions Tests are much faster, *always* wait for Tests finished and succeed. Never merge a PR, where it's Tests are failing
- Never disable Tests just because it's comfortable. For example, I saw, that Integrations Tests on Windows where disable 4 months ago.
- Disabled or ignored Tests will prevent the detection of subsequent bugs, so you cannot track down anymore which commit caused what problem (on the easy way).

One way to ensure these rules is to enable https://help.github.com/en/github/administering-a-repository/enabling-required-status-checks for the master branch. Please do not forget to tick the **Include Administrators** checkbox, otherwise you will accidentally merge without checks.

Please leave a small comment below to show that you read this message or having suggestions.

**Comment by arakis** [comment]
By the way, currently it's not possible to prevent double test, if a Tag is pushed after a commit. See https://github.community/t5/GitHub-Actions/avoid-double-builds-when-reacting-on-conditional-tag-event/m-p/34702

I'm sure they will provide such feature in the future. In the meantime, it will not hurt us.

**Comment by arakis** [comment]
Added the status check suggestion.

**Comment by tgiphil** [comment]
+1 to **Enabling required status checks**

**Comment by charsleysa** [comment]
@tgiphil this will need to be something you activate as we don't have permissions.

**Comment by tgiphil** [comment]
Done. It may require some adjustments.

**Comment by charsleysa** [comment]
Closing due to recommendations accepted and implemented.
