### ISSUE TITLE
YAML Format for Configuration

### ISSUE THREAD

**Issue by arakis** [mosa/MOSA-Project#746]
Currently, a configuration system is in Development for configuring several things. The problem is, we forget to decide to define a format in the developer's team, so accidentally a custom format was written. We should discuss this now, before launching that new features.

I would suggest YAML (or maybe JSON) as format, and strictly vote against a custom format.

The reasons for YAML:

- The custom format requires Tabs for indention. It's a known problem, that this can result in problem when copy and paste text, or while having different Indention settings in the editor. YAML format is known by the most editors and will respect their indention politics without any setup.

- YAML is fully compatible to JSON, With lossless conversion in both direction.
- With YAML you can define complex Data structures, incl. Line breaks within Text literal, and arrays.
- YAML has Syntax highlighting and Auto-Format. Mosa's config has not.

- Schema-Definition, for Auto-Completion and Validation. Like in XML/DTD-Definitions, you can define a Schema. The Schema can be used for Auto-Completion in the Editor and for Validation (at runtime or for CI/CD-Tests).

- There are several well known parsers for YAML and JSON.
- There are several well known WRITERS for YAML and JSON.
- Because of JSON-Compatibility, you can use Newtonsoft as powerfull library to merge objects, or to deserialize them to complex .NET objects structures. Even custom mappings are possible.

- Don't reinvent the wheel. It has it's matter why YAML and JSON is widely used.

Even if there are reasons that Mosa's custom has special features: The Disadvantages are in comparison to YAML much too big to get a small benefit from Mosa's custom format. And if you think there's something that's only possible with that custom format, then we should rething the configuration design. I'm working every day with Ansible and Kubernetes Configuration scripts an I can tell you, it's matter of design. With a good design and plan, nearly everything is possible, even includes.

By the way, Mosa's custom format is very similar to YAML, but breaks compatibility. So it's not so hard to go to full YAML support at this stage.

**Comment by charsleysa** [comment]
I am inclined to agree that we should use standardised formats where possible over custom formats as it increases compatibility with existing tooling as most tooling uses either YAML or JSON which when deserialised are essentially fully compatible with each other.

This opens up the possibility of having files generated by external tools with minimal effort.
