### ISSUE TITLE
Qemu - Coolworld kernel panic

### ISSUE THREAD

**Issue by jangofett4** [mosa/MOSA-Project#761]
## Host
Windows 10 x64 Home Edition
RAM: 8gb
CPU: i5 4200m

## Steps to reproduce
Clean copy of repository:
`git clone https://github.com/mosa/MOSA-Project` 
Compile:
`Compile.bat` (0 errors, 10 warnings) 
Launch:
`Launcher.bat` 
As opposed to readme.md, launcher does not automatically select Coolworld.x86, so I had to select manually. Also IMG output won't work with Qemu (Disk error), so I selected ISO instead.
These are the Settings:
![Settings](https://user-images.githubusercontent.com/19552452/72221222-9b34fa00-3569-11ea-9f38-6cbe8470bfb0.png)

Compile and Run:
![candr](https://user-images.githubusercontent.com/19552452/72221242-c6b7e480-3569-11ea-85bf-2d43e63fbb60.png)

QEMU:
![kernelpanic](https://user-images.githubusercontent.com/19552452/72221249-e2bb8600-3569-11ea-92a5-79ba3b1cd1fb.png)
'Extra' is increasing at a fast rate, I've seen it hit thousands.  
Tried changing the options (bootloader, file system) with no luck.  
Bochs says `display library 'x' not available` in windows. (using external terminal, launcher hangs using bochs)

**Comment by tgiphil** [comment]
Unselect "Inline" with the CoolWorld application. This avoid a known bug in the compiler. We are working to fix it.

**Comment by jangofett4** [comment]
Wow, not that it worked, but it boosted the compile time by at least 3 times! Now I can delve into the world of managed operating systems. Interestingly enough HelloWorld example works just fine with inline option.

**Comment by tgiphil** [comment]
When inline is enabled, methods can be recompiled multiple times. It results in excellent run-time performance but the extra work does slow down the initial compile.

**Comment by tgiphil** [comment]
Join us on Gitter (https://gitter.im/mosa/MOSA-Project). We have a new version coming out soon.
