### ISSUE TITLE
Branch Elimination

### ISSUE THREAD

**Issue by furesoft** [mosa/MOSA-Project#795]
Could you support BranchElimination?

**Comment by tgiphil** [comment]
Can you be more specific? The compiler already optimizes away unused branches.

**Comment by furesoft** [comment]
When its possible to use a non branch version of the code, replace it.

Sample:
`static int Min(int a, int b)
        {
		    if(a < b) return a;
	        else if(b >= a) return b;
        }`

would be replaced with:
`static int Min(int a, int b)
        {
            return a * Convert.ToInt32(a < b) + (b * Convert.ToInt32(b <= a));
        }`

**Comment by tgiphil** [comment]
Why? That’s much more expensive to execute, and contains one more branch. Plus obscure other optimizations.
