### ISSUE TITLE
Use uxmal (disassembler) nuget package

### ISSUE THREAD

**Issue by tgiphil** [mosa/MOSA-Project#803]
Use the nuget package when ready by developer.

**Comment by tgiphil** [comment]
https://github.com/uxmal/reko/issues/937#issuecomment-699682620

**Comment by uxmal** [comment]
You can obtain a prerelease version here:
https://www.nuget.org/packages/Reko.Decompiler.Runtime/0.9.2-prerelease
Please note that you may have some build issues as some of the classes and interfaces you're using have been refactored and/or renamed. You can reach out to me on https://gitter.im/uxmal/reko if you need my assistance.

**Comment by uxmal** [comment]
A new package is available:
https://www.nuget.org/packages/Reko.Decompiler.Runtime/0.9.2-prerelease2
