### ISSUE TITLE
How do I create a new MOSA Project?

### ISSUE THREAD

**Issue by vahin** [mosa/MOSA-Project#816]
I tried adding references to the dlls from the bin directory, and I tried to copy the Mosa.Demo.HelloWorld.x86 project from Source directory, neither of them worked. How do I create a new MOSA Project?

**Comment by tgiphil** [comment]
@vahin Chat with us on Gitter: https://gitter.im/mosa/MOSA-Project

**Comment by vahin** [comment]
@tgiphil I kindly request an answer instead of chatting, please.
