### ISSUE TITLE
Change object references to point to object's first field

### ISSUE THREAD

**Issue by tgiphil** [mosa/MOSA-Project#825]
Edited:

Change object references to point to the object's first field method table pointer rather than the object header. ~~This change is to align with Microsoft's implementation.~~ It's also simpler and allows MOSA to add additional information in the object header, if necessary.

**Comment by charsleysa** [comment]
https://devblogs.microsoft.com/premier-developer/managed-object-internals-part-1-layout/

**Comment by charsleysa** [comment]
Microsoft's implementation points to the the method table as it isn't considered to be part of the object header
https://github.com/dotnet/runtime/blob/master/src/coreclr/vm/object.h#L125

**Comment by tgiphil** [comment]
> Microsoft's implementation points to the method table as it isn't considered to be part of the object header

Good catch! We'll adjust so that the object pointer will point to the MethodTable.

**Comment by charsleysa** [comment]
> > Microsoft's implementation points to the method table as it isn't considered to be part of the object header
> 
> Good catch! We'll adjust so that the object pointer will point to the MethodTable.

I'm wondering whether we should more forward with our implementation of pointing to the first field.

The advantage of pointing to the first field is that it makes things a bit simpler as we can rely on the assumption that the pointer will always point to the start of the data.

The disadvantage is that we're no longer aligned with Microsoft's implementation.

Thoughts?

**Comment by tgiphil** [comment]
One downside is how pointers to structures are handled now - offsets are no required to work around the missing method table pointer.  UnboxValueTypeStage is now gone for example.
