### ISSUE TITLE
Metadata - Second Iteration

### ISSUE THREAD

**Issue by charsleysa** [mosa/MOSA-Project#85]
Hi all,

So the first iteration of Metadata, Runtime and Reflection has been completed and is working fine.
In light of that, I've been looking at how to best implement the rest of the Reflection features and have found that in .NET 4.5 they changed up the model on how it all works by splitting it in two.
The model takes the references and definitions approach where everything in metadata is either a reference of a definition. For example, the Type class would be used for references and would only expose shallow information such as TypeName, while the TypeInfo class would be used for definitions and would expose the in-depth information.

Now, this new model actually seems like a better approach to take as it is simpler and should allow us to implement a lot of Reflection features faster while maintaining portability and performance.
The new model removes a lot of the features existing in the old model but in turn this drastically improves performance (note: in .NET 4.5 they keep they old model as well for backwards compatibility).

What I see happening with the Second Iteration is one of two things:
1) We stick with the classic Reflection model and keep the monolithic sized Reflection API; or
2) We adopt the new .NET 4.5 Reflection model and implement only the new model with none of backwards compatibility.

Thoughts?

**Comment by charsleysa** [comment]
@tgiphil Progress has been made.

Type Activator is now available but only works for Types with a parameterless constructor (which most types have).

Also I have updated the DeviceDriverRegistry to detect PCI and ISA driver attributes and build them.

Currently there seems to be a bug with the Custom Attributes Data in which the values for the NamedArguments are not being found correctly, which is why the DeviceDriverRegistry reports that no drivers are found.

I'm off on holiday on Thursday for a week so I'll be MIA until I get back.

**Comment by tgiphil** [comment]
Great news! Keep up the excellent work and enjoy the holidays!

**Comment by charsleysa** [comment]
@tgiphil fixed the bug with custom attributes. That all loads fine now.

The system can now find drivers and try loading them but it fails during the loading stage (so somewhere between Type Activator usage and starting the driver).

If you could please take a look at my metadata branch, you might be able to pick up what I'm doing wrong.

**Comment by charsleysa** [comment]
@tgiphil we have liftoff!!!

I have finally finished the second iteration and now have drivers successfully loading through Reflection!

**Comment by tgiphil** [comment]
@charsleysa Perfect!
