### ISSUE TITLE
MOSA Launcher window works incorrectly

### ISSUE THREAD

**Issue by tihonryzhikov** [mosa/MOSA-Project#851]
Why does the launcher have such a window?
I'm using the last version of MOSA.
![изображение_2021-08-24_141451](https://user-images.githubusercontent.com/66679206/130606955-ab56d70c-4a26-46db-8809-1f7575d2ccaf.png)
Please help

**Comment by tgiphil** [comment]
@tihonryzhikov I'm not seeing that occur in the master branch. Can you provide more information?
