### ISSUE TITLE
Mouse not working on real hardware

### ISSUE THREAD

**Issue by ArtGo-Devloppper** [mosa/MOSA-Project#854]
Hello
I'm starting to use Mosa, I've coded an OS with a mouse, in virtualBox I have no problem but on a real PC the mouse doesn't work, is this a bug?
Thank you

**Comment by nifanfa** [comment]
> @nifanfa I used your repo "Mosa-Core" and "Mosa-GUI-Sample" but the mouse still does not work 

we only support ps2 mouse. usb mouse is not supported. and if you bios support legacy mouse support you can enable it and then your usb mouse will as a ps2 mouse

**Comment by nifanfa** [comment]
and it works on my pc with usb mouse. sometimes it called "port 60 emulation"

**Comment by ArtGo-Devloppper** [comment]
Thank you for your answer but is the creation of a USB driver planned?

**Comment by nifanfa** [comment]
> Thank you for your answer but is the creation of a USB driver planned?

USB is very complicated. I don't know what i should do first
