### ISSUE TITLE
Add support for Syslinux 6.03 (latest version)

### ISSUE THREAD

**Issue by tgiphil** [mosa/MOSA-Project#908]
* Complete the implementation of Mosa.Utility.BootImage.Syslinux.PatchSyslinux_6_03() method.
* Use  syslinux_patch() method as reference in syslxmod.c at https://repo.or.cz/syslinux.git/blob/05ac953c23f90b2328d393f7eecde96e41aed067:/libinstaller/syslxmod.c#l107

**Comment by AnErrupTion** [comment]
This should be closed as Limine has been implemented.

**Comment by tgiphil** [comment]
Closing due to transition to Limine bootloader
