### ISSUE TITLE
BUG: Switches with more than 6 cases prevent the OS from being compiled

### ISSUE THREAD

**Issue by Dawid8plc** [mosa/MOSA-Project#956]
It appears that when there is a switch with 7 or more cases, the OS doesn't get compiled into a .bin file to the Local/Temp/MOSA folder, and therefore the previous compiled bin file is launched by QEMU, and if there wasn't one, launcher will fail to launch the emulator.

I tried to add a new app to the Shell.cs file from the CoolWorld demo project, like so:

![image](https://user-images.githubusercontent.com/16761816/144710742-4bcc91b7-6573-4af1-ab23-66145fa2474e.png)

And it would prevent the OS from being compiled.

**Comment by AnErrupTion** [comment]
@Dawid8plc Does it also happen when you ``return null`` instead of ``return new DTest()``?

**Comment by Dawid8plc** [comment]
Yes, it also happens with `return null`

**Comment by AnErrupTion** [comment]
Yup, seems to fail with ``Exception- Method: <PrivateImplementationDetails>::ComputeStringHash(System.String):System.UInt32 -> Mosa.Compiler.Common.Exceptions.CompilerException: ValueNumbering Stage: Expected PHI instruction but found instead: 0002C: IR.Move32 v25 [I4] <= v24 [I4] for v24 [I4]``.

**Comment by AnErrupTion** [comment]
However, it works without optimizations (ValueNumbering is an optimization).

**Comment by Dawid8plc** [comment]
If I disable value numbering however, none of the commands work anymore.
![image](https://user-images.githubusercontent.com/16761816/163401696-76a9e8d6-2597-4e80-8f17-af32d413957a.png)

**Comment by AnErrupTion** [comment]
@Dawid8plc I recommend disabling all optimizations as a whole (that's what I did).

**Comment by Dawid8plc** [comment]
I see, it appears to be working just fine with all of them off.
