### ISSUE TITLE
Bad capture of buttons by ReadKey ()

### ISSUE THREAD

**Issue by 85oskxr** [mosa/MOSA-Project#965]
When I try to intercept a key with the ReadKey () method, when I press the left arrow key it recognizes it as the number 4. Is there any way to fix it?

**Comment by AnErrupTion** [comment]
@Ve-NoX Is it when using ``GraphicalConsole.ReadKey()``?

**Comment by Ve-NoX** [comment]
@AnErrupTion  this happens when using the Console.ReadLine()/Console.ReadKey() method

**Comment by AnErrupTion** [comment]
No such methods exist inside ``System.Console``. @Ve-NoX

**Comment by Ve-NoX** [comment]
@AnErrupTion I'm using this MOSA version: v1.9.7.70 (Visual Studio MOSA Project Template exe)

**Comment by AnErrupTion** [comment]
Oh, could you please try with v2.1?
