### ISSUE TITLE
BUG: Arguments causing a kernel panic

### ISSUE THREAD

**Issue by Ziocash** [mosa/MOSA-Project#983]
How to reproduce:

- Write a `Start` method inherited from `IConsoleApp`
- Insert an argument in CoolWorld.x86

![image](https://user-images.githubusercontent.com/31541164/182483676-a1e943e1-ab10-4e50-8a60-2a2316b58484.png)

![image](https://user-images.githubusercontent.com/31541164/182484278-890689cc-032c-412f-8f8b-be6222b2f31d.png)

![image](https://user-images.githubusercontent.com/31541164/182484334-1556a13e-b888-4154-ada8-3f823624e5a1.png)

I'm currently looking for a solution to this problem, but poor results for now

**Comment by tgiphil** [comment]
Recreatable:

```
public class Test : BaseApplication, IConsoleApp
{
	public override int Start(string parameters)
	{
		if (string.IsNullOrEmpty(parameters))
		{
			Console.WriteLine("missing paramter");
			return 1;
		}

		Console.WriteLine(parameters);

		return 0;
	}
}
```

**Comment by tgiphil** [comment]
Closing... unable to test since the code base for this has been refactored.
